// <auto-generated />
using InventorySystem.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace InventorySystem.Migrations
{
    [DbContext(typeof(InventoryContext))]
    [Migration("20200925035251_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("InventorySystem.Models.Product", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasColumnType("int(10)");

                    b.Property<bool>("IsDiscontinued")
                        .HasColumnType("BOOLEAN");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(30)")
                        .HasAnnotation("MySql:CharSet", "utf8mb4")
                        .HasAnnotation("MySql:Collation", "utf8mb4_general_ci");

                    b.Property<int>("Quantity")
                        .HasColumnType("int(10)");

                    b.HasKey("ID");

                    b.ToTable("product");

                    b.HasData(
                        new
                        {
                            ID = -1,
                            IsDiscontinued = false,
                            Name = "Chair",
                            Quantity = 5
                        },
                        new
                        {
                            ID = -2,
                            IsDiscontinued = false,
                            Name = "Table",
                            Quantity = 3
                        },
                        new
                        {
                            ID = -3,
                            IsDiscontinued = false,
                            Name = "Pen",
                            Quantity = 0
                        },
                        new
                        {
                            ID = -4,
                            IsDiscontinued = false,
                            Name = "Pencil",
                            Quantity = 6
                        },
                        new
                        {
                            ID = -5,
                            IsDiscontinued = false,
                            Name = "Cardboard",
                            Quantity = 10
                        },
                        new
                        {
                            ID = -6,
                            IsDiscontinued = false,
                            Name = "Desk",
                            Quantity = 0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
